// Flags =  2 float , 4 unsigned , 8 short , 64 dfloat (sim only)  (see more options in the CCmdMode definition)
		{ 0 , (long unsigned *) & CanStat.CanCtl },
		{ 0 , (long unsigned *) & IsrTimerPD.UsecTimer }, //:UsecTimer [Time]
        { 0 , (long unsigned *) & IsrTimerPD.FastUsecTimer }, //:FastUsecTimer [Time]
		{ 0 , (long unsigned *) & CanStat.CanCtl }, //4:CanCtl [Debug]
		{ 2 , (long unsigned *) & ClaState.Filt.Volts24}, //:Volts24  [Analog]
		{ 2 , (long unsigned *) & ClaState.Filt.VServo},//:VServo [Analog]
		{ 2 , (long unsigned *) & ClaState.Filt.CurServo},//:CurServo [Analog]
		{ 2 , (long unsigned *) & ClaState.Filt.V36}, //:V36 [Analog]
		{ 2 , (long unsigned *) & ClaState.Filt.VBat54[0]}, //:VBat54_0 [Analog]
		{ 2 , (long unsigned *) & ClaState.Filt.VBat54[1]}, //:VBat54_1 [Analog]
		{ 2 , (long unsigned *) & ClaState.Filt.Volts12[0]}, //:Volts12_0 [Analog]
		{ 2 , (long unsigned *) & ClaState.Filt.Volts12[1]}, //:Volts12_1 [Analog]
		{ 2 , (long unsigned *) & ClaState.Filt.Cur5},  //:Cur5 [Analog]
		{ 2 , (long unsigned *) & ClaState.Filt.Volts5}, //:Volts5 [Analog]
		{ 2 , (long unsigned *) & ClaState.Filt.Cur24},  //:Cur24 [Analog]
		{ 2 , (long unsigned *) & ClaState.Filt.Cur12},   //:Cur12 [Analog]
		{ 12, (long unsigned *) & Buck12Control.Exception},   //:Buck12_Exception [VoltReg]
		{ 12, (long unsigned *) & Buck12Control.MotorOn} ,   //:Buck12_MotorOn [VoltReg]
		{ 2 , (long unsigned *) & Buck12Control.VSetPoint},  //:Buck12_VSetPoint [VoltReg]
        { 2 , (long unsigned *) & Buck12Control.ValOut},  //:Buck12_ValOut [VoltReg]
        { 2 , (long unsigned *) & ClaState.V12NowRatio},  //:V12NowRatio [VoltReg]
        { 2 , (long unsigned *) & ClaState.V12FinalRatio},  //:V12FinalRatio [VoltReg]
        { 12, (long unsigned *) & Buck12Control.pwm} ,   //:Buck12_pwm [VoltReg]
        { 12, (long unsigned *) & Buck24Control.Exception},   //:Buck24_Exception [VoltReg]
		{ 12, (long unsigned *) & Buck24Control.MotorOn} ,   //:Buck24_MotorOn [VoltReg]
		{ 2 , (long unsigned *) & Buck24Control.VSetPoint} , //:Buck24_VSetPoint [VoltReg]
        { 2 , (long unsigned *) & Buck24Control.ValOut},  //:Buck24_ValOut [VoltReg]
        { 12, (long unsigned *) & Buck24Control.pwm} ,   //:Buck24_pwm [VoltReg]
        { 2 , (long unsigned *) & ClaState.V24NowRatio},  //:V24NowRatio [VoltReg]
        { 2 , (long unsigned *) & ClaState.V24FinalRatio},  //:V24FinalRatio [VoltReg]
        { 2 , (long unsigned *) & Sw54Control.ValOut} , //:Sw54ValOut [VoltReg]
        { 12 , (long unsigned *) & Sw54Control.Exception},  //:Sw54Exception [VoltReg]
        { 12 , (long unsigned *) & Sw54Control.MotorOn},  //:Sw54MotorOn [VoltReg]
        { 12 , (long unsigned *) & Sw54Control.pwm},  //:Sw54pwm [VoltReg]
        { 12 , (long unsigned *) & Sw54Control.Ready},  //:Sw54ServoRdy [VoltReg]
        { 2 , (long unsigned *) & ClaState.V54NowRatio},  //:V54NowRatio [VoltReg]
		{ 12, (long unsigned *)& ManCmd.State }, //:State [ManState]
		{ 12, (long unsigned *)& ManCmd.ControlWord}, //:CtrlWord [ManState]
		{ 12, (long unsigned *)& ManCmd.ControlWordCopy}, //:CtrlWordCopy [ManState]
        { 2 , (long unsigned *)& Debug[0] }, //:Debug0 [Motion]
        { 2 , (long unsigned *)& Debug[1] }, //:Debug1 [Motion]
        { 2 , (long unsigned *)& Debug[2] }, //:Debug2 [Motion]
        { 0 , (long unsigned *) & CanStatistics.SdoCobCnt }, //:SdoCobCnt [Communication]
        { 12 , (long unsigned *) &  CanStatistics.UloadSdoResponseCnt  }, //:UloadSdoResponseCnt [Communication]
        { 12 , (long unsigned *) &  CanStatistics.TotalRxCnt  }, //:TotalRxCnt [Communication]
        { 0 , (long unsigned *) &  CanStatistics.MaxRxBoxLoad  }  //:MaxRxBoxLoad [Communication]
