xcopy /y C:\Yahali\Nimrod\Drivers\BootIntfc\Flash_Lib\BootInterface.out .\Exe\*.*
xcopy /y C:\Yahali\Nimrod\Drivers\BootWheel\Flash_Lib\WheelBoot.out .\Exe\*.*
xcopy /y C:\Yahali\Nimrod\Drivers\Neck37\Flash_Lib\NeckDrive.out .\Exe\*.*
xcopy /y C:\Yahali\Nimrod\Drivers\PD2_023\CPU1_FLASH\PD2_023.out .\Exe\*.*
xcopy /y C:\Yahali\Nimrod\Drivers\Wheel37\Flash_Lib\WheelPower.out .\Exe\*.*
xcopy /y C:\Yahali\Nimrod\Drivers\WheelIntfc37\CPU1_FLASH\WheelInterface.out .\Exe\*.*
xcopy /y C:\Yahali\Nimrod\Drivers\Neck37\Flash_Lib\NeckDrive.hex .\Exe\*.*
xcopy /y C:\Yahali\Nimrod\Drivers\Wheel37\Flash_Lib\WheelPower.hex .\Exe\*.*
xcopy /y C:\Yahali\Nimrod\Drivers\WheelIntfc37\CPU1_FLASH\WheelInterface.hex .\Exe\*.*
xcopy /y C:\Yahali\Nimrod\Drivers\BootNeck\Flash_Lib\NeckBoot.out .\Exe\*.*