/*
 * BlTimerAlloc.h
 *
 *  Created on: Aug 17, 2021
 *      Author: Yahali
 */

#ifndef APPLICATION_BLTIMERALLOC2_H_
#define APPLICATION_BLTIMERALLOC2_H_


/*
 * TimerAlloc.h
 *
 *  Created on: Dec 23, 2016
 *      Author: Yahali Theodor
 */

#ifndef APPLICATION_LPTIMERALLOC_H_
#define APPLICATION_LPTIMERALLOC_H_

//#define NSYS_TIMER_CMP_ARRAY 128

// Timers
// Up to NSYS_TIMER_CMP_ARRAY defined
// These timers codes are reserved, DO NOT change
#define TIMER_ARR_STAM_WAIT_IDLE 0 // Reserved
#define TIMER_ARR_RESET_BOOTUP  1  // Reserved
#define TIMER_ARR_RESET_TOTAL_BOOTUP  2 // Reserved

#define TIMER_RS485_24V_TOUT  4
#define TIMER_RS485_24V_TWAIT 5
#define TIMER_RS485_12V_TWAIT 6
#define TIMER_RS485_24V_TWAIT_RT 7
#define TIMER_POWER_UP_SEQUENCER 8

#define TIMER_PREOP_ALLOW_TIME 9

// The space 10 ... 39 is used for axis management, dont insert other timers there
#define TMR_24V_AXIS_MNG 10
#define TMR_12V_AXIS_MNG 25
#define TMR_AXIS_LAST 39

#define TMR_WAIT_SUCK_ACT 41
#define TMR_DYN12_CYCLE 42
#define TMR_DYN24_CYCLE 43

#define TIMER_RS485_12V_TOUT  44
#define TIMER_DYNAMIXEL_ON_TMR12 45
#define TIMER_DYNAMIXEL_ON_TMR24 46
#define TIMER_MAN_TOUT 47
#define TIMER_PBIT 48

#define TMR_WAIT_SUCK_CHNG 58
#define TMR_WAIT_SUCK_DEPLETE 59
#define TMR_WAIT_SUCK_HOLD 60
#define TMR_MUSHROOM_PRESS 61

#define TMR_WAIT_LASER_READ 62
#define TMR_WAIT_STDBY  63
#define TMR_WAIT_LASER_INVALID 64
#define TMR_WAIT_PACK_RELEASE 65
#define TMR_24V_RESTART 66
#define TMR_LASER_START 67
#define TMR_DOOR_STOP 68

#define TIMER_REBOOT_TIME12 69
#define TIMER_REBOOT_TIME24 70

#define TIMER_MAN_RECOVERY 71

#define TMR_MANIP_MON 72
#define TMR_STOP_MON  73

#define TMR_WAIT_MAN_FPOS 74
#define TMR_ATP_RS485 75

#define TMR_PREPARE_TMR 76
#define TMR_PREPARE_STABILIZE_TMR 77

#define TIMER_12_TOUT_START 80
#define TIMER_24_TOUT_START 90
#define TIMER_24_TOUT_END   99

#define TIMER_BRAKE_ENGAGE 100
#define TIMER_PRESLEEP 101
#define TIMER_I_SLEEP_LET_ME_SNORE 102
#define TIMER_ARR_GEN_WAIT_CAN_MGR 103
#define TIMER_I2C_TLC_TRANSMIT 104
//#define TIMER_POT_PROBLEM 105
#define TIMER_PS_MNGR_PERIOD 106
#define TIMER_WAIT_PS 107
#define TIMER_PACK_MON_HELPER 108
#define TIMER_PACK_MON_HELPER2 109
#define TIMER_PD_DATA_RX_TOUT 110


//#define TIMER_MANUAL_MAN_CMD_TIMEOUT 42

#endif /* APPLICATION_LPTIMERALLOC_H_ */



#endif /* APPLICATION_BLTIMERALLOC2_H_ */
