// Flags =  0 : long , 2 float , 4 unsigned long
        { 0 , (long unsigned *) & SysTimerStr.SysTimer }, //:UsecTimer [Time]
        { 0 , (long unsigned *)& ManCmd.State }, //:State [ManState]
        { 2 , (long unsigned *)& ManCmd.x }, //:x [ManState]
        { 2 , (long unsigned *)& ManCmd.XTarget }, //:XTarget [ManTarget]
        { 2 , (long unsigned *)& ManCmd.y }, //:y [ManState]
        { 2 , (long unsigned *)& ManCmd.YTarget }, //:YTarget [ManTarget]
        { 2 , (long unsigned *)& ManCmd.Ctl24[0].Pos }, //:ShoulderPos [Shoulder]
        { 2 , (long unsigned *)& ManCmd.Ctl24[0].Speed }, //:ShoulderSpeed [Shoulder]
        { 2 , (long unsigned *)& ManCmd.Ctl24[0].SpeedCmd }, //:ShoulderSpeedCmd [Shoulder]
        { 0, (long unsigned *)& ManCmd.Ctl24[0].IsStopped }, //:ShoulderIsStopped [Shoulder]
        { 0 , (long unsigned *)& ManCmd.Ctl24[0].IsPosDone }, //:ShoulderIsPosDone [Shoulder]
        { 0 , (long unsigned *)& DynStat24[0].CombinedState} , //:ShoulderCombinedState [Shoulder]
        { 2 , (long unsigned *)& ManCmd.Ctl24[0].Profiler.PosTarget }, //:ShoulderPosTgt [Shoulder]
        { 2 , (long unsigned *)& ManCmd.Ctl24[0].Profiler.ProfilePos }, //:ShoulderProfilePos [Shoulder]
        { 2 , (long unsigned *)& ManCmd.Ctl24[0].Profiler.UnfilteredPos }, //:ShoulderUnfilteredPos [Shoulder]
        { 2 , (long unsigned *)& ManCmd.Ctl24[0].Profiler.PosDiff }, //:ShoulderProfilePosDiff [Shoulder]
        { 2 , (long unsigned *)& ManCmd.Ctl24[0].Profiler.ProfileSpeed }, //:ShoulderProfileSpeed [Shoulder]
        { 2 , (long unsigned *)& ManCmd.Ctl24[0].PosErr }, //:ShoulderPosErr [Shoulder]
        { 2 , (long unsigned *)& ManCmd.Ctl24[0].OverErrorBit.State} , //:ShoulderTrkErrState [Shoulder]
        { 2 , (long unsigned *)& ManCmd.Ctl24[1].Pos }, //:ElbowPos [Elbow]
        { 2 , (long unsigned *)& ManCmd.Ctl24[1].Profiler.PosTarget }, //:ElbowPosTgt [Elbow]
        { 2 , (long unsigned *)& ManCmd.Ctl24[1].Speed }, //:ElbowSpeed [Elbow]
        { 2 , (long unsigned *)& ManCmd.Ctl24[1].SpeedCmd }, //:ElbowSpeedCmd [Elbow]
        { 0 , (long unsigned *)& ManCmd.Ctl24[1].IsStopped }, //:ElbowIsStopped [Elbow]
        { 0 , (long unsigned *)& ManCmd.Ctl24[1].IsPosDone }, //:ElbowIsPosDone [Elbow]
        { 0 , (long unsigned *)& DynStat24[1].CombinedState} , //:ElbowCombinedState [Shoulder]
        { 2 , (long unsigned *)& ManCmd.Ctl24[1].Profiler.ProfilePos }, //:ElbowProfilePos [Elbow]
        { 2 , (long unsigned *)& ManCmd.Ctl24[1].Profiler.UnfilteredPos }, //:ElbowUnfilteredPos [Elbow]
        { 2 , (long unsigned *)& ManCmd.Ctl24[1].Profiler.PosDiff }, //:ElbowProfilePosDiff [Elbow]
        { 2 , (long unsigned *)& ManCmd.Ctl24[1].Profiler.ProfileSpeed }, //:ElbowProfileSpeed [Elbow]
        { 2 , (long unsigned *)& ManCmd.Ctl24[1].PosErr }, //:ElbowCtlPosErr [Elbow]
        { 2 , (long unsigned *)& ManCmd.Ctl24[1].OverErrorBit.State} , //:ElbowTrkErrState [Elbow]
        { 2 , (long unsigned *)& ManCmd.Ctl24[2].Pos }, //:WristPos [Wrist]
        { 2 , (long unsigned *)& ManCmd.Ctl24[2].Speed }, //:WristSpeed [Wrist]
        { 2 , (long unsigned *)& ManCmd.Ctl24[2].SpeedCmd }, //:WristSpeedCmd [Wrist]
        { 0, (long unsigned *)& ManCmd.Ctl24[2].IsStopped }, //:WristIsStopped [Wrist]
        { 0, (long unsigned *)& ManCmd.Ctl24[2].IsPosDone }, //:WristIsPosDone [Wrist]
        { 2 , (long unsigned *)& ManCmd.Ctl24[2].Profiler.PosTarget }, //:WristPosTgt [Wrist]
        { 2 , (long unsigned *)& ManCmd.Ctl24[2].Profiler.ProfilePos }, //:WristProfilePos [Wrist]
        { 2 , (long unsigned *)& ManCmd.Ctl24[2].Profiler.UnfilteredPos }, //:WristUnfilteredPos [Wrist]
        { 2 , (long unsigned *)& ManCmd.Ctl24[2].Profiler.PosDiff }, //:WristProfilePosDiff [Wrist]
        { 2 , (long unsigned *)& ManCmd.Ctl24[2].Profiler.ProfileSpeed }, //:WristProfileSpeed [Wrist]
        { 2 , (long unsigned *)& ManCmd.Ctl24[2].PosErr }, //:WristCtlPosErr [Wrist]
        { 2 , (long unsigned *)& ManCmd.Ctl24[2].OverErrorBit.State} , //:WristTrkErrState [Wrist]
        { 2 , (long unsigned *)& ManCmd.Ctl12[0].Pos }, //:LeftLockPos [LDoor]
        { 2 , (long unsigned *)& ManCmd.Ctl12[0].L12.PosTarget }, //:LeftLockPosTgt [LDoor]
        { 2 , (long unsigned *)& ManCmd.Ctl12[0].Speed }, //:LeftLockSpeed [LDoor]
        { 0, (long unsigned *)& ManCmd.Ctl12[0].IsStopped }, //:LeftLockIsStopped [LDoor]
        { 0, (long unsigned *)& ManCmd.Ctl12[0].IsPosDone }, //:LeftLockIsPosDone [LDoor]
        { 2 , (long unsigned *)& ManCmd.Ctl12[1].Pos }, //:RightLockPos [RDoor]
        { 2 , (long unsigned *)& ManCmd.Ctl12[1].L12.PosTarget }, //:RightLockPosTgt [RDoor]
        { 2 , (long unsigned *)& ManCmd.Ctl12[1].Speed }, //:RightLockSpeed [RDoor]
        { 0, (long unsigned *)& ManCmd.Ctl12[1].IsStopped }, //:RightLockIsStopped [RDoor]
        { 0, (long unsigned *)& ManCmd.Ctl12[1].IsPosDone }, //:RightLockIsPosDone [RDoor]
        { 2 , (long unsigned *)& SysState.Package.LaserDist }, //:LaserDist [ManState]
        { 2 , (long unsigned *)& SysState.Package.LaserDistMedian }, //:LaserDistMedian [ManState]
        { 0 , (long unsigned *)& SysState.Package.LaserDistValid }, //:LaserDistValid [ManState]
        { 0 , (long unsigned *)& SysState.Package.LaserMedianValid }, //:LaserMedianValid [ManState]
        { 0, (long unsigned *)& ManCmd.ControlWord}, //:CtrlWord [ManState]
        { 0, (long unsigned *)& ManCmd.ControlWordCopy}, //:CtrlWordCopy [ManState]
        { 0, (long unsigned *)& SysState.Package.SuckRequest.ul}, //:SuckRequest [Pump]
        { 0, (long unsigned *)& SysState.Package.SuckCmd.ul}, //:SuckCmd [Pump]
        { 0, (long unsigned *)& SysState.Pump.On}, //:PumpOn [Pump]
        { 0, (long unsigned *)& SysState.Pump.IsHolding}, //:PumpIsHolding [Pump]
        { 0, (long unsigned *)& SysState.Pump.IsDepleted}, //:PumpIsDepleted [Pump]
        { 2, (long unsigned *)& DynStat24[0].SpeedActual }, //:ShoulderSpeedAct [Motion]
        { 2, (long unsigned *)& DynStat24[0].PositionActual }, //:ShoulderPosAct [Motion]
        { 0, (long unsigned *)& DynStat24[0].MotorOn }, //:ShoulderMotorOn [Motion]
        { 0, (long unsigned *)& DynStat24[0].HardErrorStat }, //:ShoulderError [Motion]
        { 2, (long unsigned *)& DynStat24[1].SpeedActual }, //:ElbowSpeedAct [Motion]
        { 2, (long unsigned *)& DynStat24[1].PositionActual }, //:ElbowPosAct [Motion]
        { 0, (long unsigned *)& DynStat24[1].HardErrorStat }, //:ElbowError [Motion]
        { 2, (long unsigned *)& DynStat24[2].SpeedActual }, //:WristSpeedAct [Wrist]
        { 2, (long unsigned *)& DynStat24[2].PositionActual }, //:WristPosAct [Wrist]
        { 0, (long unsigned *)& DynStat24[2].HardErrorStat }, //:WristError [Wrist]
        { 2, (long unsigned *)& DynStat24[0].CurrentActual }, //:CurrentActual0 [Shoulder]
        { 2, (long unsigned *)& DynStat24[1].CurrentActual }, //:CurrentActual1 [Elbow]
        { 2, (long unsigned *)& DynStat24[2].CurrentActual }, //:CurrentActual2 [Wrist]
        { 2 , (long unsigned *)& TTProfile.Xnow }, //:TTProfileX [Motion]
        { 2 , (long unsigned *)& TTProfile.Ynow }, //:TTProfileY [Motion]
        { 2 , (long unsigned *)& XYTraj.rho }, //:XYTrajrho [CartezianMot]
        { 2 , (long unsigned *)& XYTraj.tTraj }, //:XYTrajt [CartezianMot]
        { 2 , (long unsigned *)& XProfile.ProfilePos }, //:XProfilePos [CartezianMot]
        { 2 , (long unsigned *)& XProfile.ProfileSpeed }, //:XProfileSpeed [CartezianMot]
        { 0, (long unsigned *)& ManCmd.StopError}, //:ManStopError [ManState]
        { 0 , (long unsigned *) & CommStatistics24[0] }, //:CommStatisticsSh [Communication]
        { 0 , (long unsigned *) &  CommStatistics24[1]  }, //:CommStatisticsEl [Communication]
        { 0 , (long unsigned *) &  CommStatistics24[2]  }, //:CommStatisticsWr [Communication]
        { 0 , (long unsigned *) &  ManCmd.Recovery24.RecoveryAttemptCounter}, //:RecoveryCounterAndState [ManState]
        { 0 , (long unsigned *) & StructManipDbg.stat }, //:StructManipDbg [ManDbg]
        { 2 , (long unsigned *) & StructManipDbg.BigErr }, //:BigErr [ManDbg]
        { 2 , (long unsigned *) & StructManipDbg.BigfErr }, //:BigfErr [ManDbg]
        { 2, (long unsigned *)& DynStat12[0].PositionActual }, //:LeftDoorPosAct [Motion]
        { 2, (long unsigned *)& DynStat12[1].PositionActual }, //:RightDoorPosAct [Motion]
        { 0, (long unsigned *)& DynStat12[0].PositionCnt }, //:Dyn12PosCnt0 [Motion]
        { 0, (long unsigned *)& DynStat12[1].PositionCnt }, //:Dyn12PosCnt1 [Motion]
        { 0 , (long unsigned *) & DynStat12[0].Statistic1 } , //:DynStat12_0Statistic1 [Debug]
        { 0 , (long unsigned *) & DynStat12[1].Statistic1 } , //:DynStat12_1Statistic1 [Debug]
        { 0 , (long unsigned *) &  Dynamixel12.DStatistic1 } , //:DStatistic1 [Debug]
        { 0 , (long unsigned *) &  Dynamixel12.DStatistic2 } , //:DStatistic2 [Debug]
        { 0 , (long unsigned *) & ManStatistics },  //:ManStatistics [ManState]
        //        { 2 , (long unsigned *) & RecTest.f }, //:Test2 [Time]
        //        { 12 , (long unsigned *) & RecTest.u }, //:Test3 [Time]
