     { .ind = 0 ,  .Flags = CFG_FLOAT , .ptr = (float*) &SysState.MCanSupport.MinInterMessage, .lower =  0.002f,.upper = 0.1f, .defaultVal = 0.006 },// :MinInterMessage [Timing] {minimum estimate for communication cycle}
     { .ind = 1 ,  .Flags = CFG_FLOAT , .ptr = (float*) &SysState.MCanSupport.MaxInterMessage, .lower =  0.002f,.upper = 0.1f, .defaultVal = 0.010 },// :MaxInterMessage [Timing] {maximum estimate for communication cycle}
     { .ind = 2 ,  .Flags = CFG_FLOAT , .ptr = (float*) &SysState.MCanSupport.NomInterMessageTime, .lower =  0.002f,.upper = 0.1f, .defaultVal = 0.008192},// :NomInterMessageTime [Timing] {Nominal time for communication cycle}
     { .ind = 3 ,  .Flags = 0 , .ptr = (float*) &ClaState.Encoder1.EncoderOnZero, .lower =  -2147000000.0f,.upper = 2147000000.0f, .defaultVal = 0 },// :EncoderOnZero [Encoder] {Encoder offset for homing}
     { .ind = 4 ,  .Flags = CFG_FLOAT , .ptr = (float*) &ClaControlPars.IsRailSensorPNP, .lower =  0.0f,.upper = 1.01f, .defaultVal = 1.0f},// :IsRailSensorPNP [RailSensor] { 1 if rail sensor is PNP, 0 if NPN}
     { .ind = 5 ,  .Flags = CFG_FLOAT , .ptr = (float*) &ClaControlPars.Enc2MeterShelf, .lower = 1.0e-6f ,.upper = 1.0e-3f, .defaultVal = 6.5796e-05f},// :Enc2MeterShelf [RailSensor] {Encoder coefficient to meter on the shelf}
     { .ind = 6 ,  .Flags = CFG_FLOAT , .ptr = (float*) &ClaControlPars.MaxSwitchLengthMeter[0], .lower = 1.0e-3f ,.upper = 1.0e-1f, .defaultVal = 0.035f },// :MaxSwitchLengthMeter0 [RailSensor] {Maximum possible length for optical tab 0}
     { .ind = 7 ,  .Flags = CFG_FLOAT , .ptr = (float*) &ClaControlPars.MaxSwitchLengthMeter[1], .lower = 1.0e-3f ,.upper = 1.0e-1f, .defaultVal = 0.035f },// :MaxSwitchLengthMeter1 [RailSensor] {Maximum possible length for optical tab 1}
     { .ind = 8 ,  .Flags = CFG_FLOAT , .ptr = (float*) &ClaControlPars.MaxSwitchLengthMeter[2], .lower = 1.0e-3f ,.upper = 1.0e-1f, .defaultVal = 0.035f },// :MaxSwitchLengthMeter2 [RailSensor] {Maximum possible length for optical tab 2}
     { .ind = 9 , .Flags = CFG_FLOAT , .ptr = (float*) &ClaControlPars.MaxSwitchLengthMeter[3], .lower = 1.0e-3f ,.upper = 1.0e-1f, .defaultVal = 0.035f },// :MaxSwitchLengthMeter3 [RailSensor] {Maximum possible length for optical tab 3}
     { .ind = 10 , .Flags = CFG_FLOAT , .ptr = (float*) &ClaControlPars.MinSwitchLengthMeter[0], .lower = 1.0e-3f ,.upper = 1.0e-1f, .defaultVal = 0.012f },// :MinSwitchLengthMeter0 [RailSensor] {Minimum possible length for optical tab 0}
     { .ind = 11 , .Flags = CFG_FLOAT , .ptr = (float*) &ClaControlPars.MinSwitchLengthMeter[1], .lower = 1.0e-3f ,.upper = 1.0e-1f, .defaultVal = 0.012f },// :MinSwitchLengthMeter1 [RailSensor] {Minimum possible length for optical tab 1}
     { .ind = 12 , .Flags = CFG_FLOAT , .ptr = (float*) &ClaControlPars.MinSwitchLengthMeter[2], .lower = 1.0e-3f ,.upper = 1.0e-1f, .defaultVal = 0.012f },// :MinSwitchLengthMeter2 [RailSensor] {Minimum possible length for optical tab 2}
     { .ind = 13 , .Flags = CFG_FLOAT , .ptr = (float*) &ClaControlPars.MinSwitchLengthMeter[3], .lower = 1.0e-3f ,.upper = 1.0e-1f, .defaultVal = 0.012f },// :MinSwitchLengthMeter3 [RailSensor] {Minimum possible length for optical tab 3}
     { .ind = 14 , .Flags = CFG_FLOAT , .ptr = (float*) &ClaControlPars.RailSensorPNPThold, .lower = 1.0e-3f ,.upper = 4.0f, .defaultVal = 1.5f },// :RailSensorPNPThold [RailSensor] {Threshold for rail  sensor, PNP case}
     { .ind = 15 , .Flags = CFG_FLOAT , .ptr = (float*) &ClaControlPars.RailSensorNPNThold, .lower = 1.0e-3f ,.upper = 4.0f, .defaultVal = 0.8f },// :RailSensorNPNThold [RailSensor] {Threshold for rail  sensor, NPN case}
