################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
OPT_SRCS += \
../AXIS_CPU1/ccsObjs.opt 

ASM_SRCS += \
../AXIS_CPU1/Adc.asm \
../AXIS_CPU1/AppIsr.asm \
../AXIS_CPU1/AppIsr2.asm \
../AXIS_CPU1/CanDriver.asm \
../AXIS_CPU1/CanResponser.asm \
../AXIS_CPU1/CanSlave.asm \
../AXIS_CPU1/ClaAdcDrv.asm \
../AXIS_CPU1/ClaDrv.asm \
../AXIS_CPU1/Dynamixel.asm \
../AXIS_CPU1/ECap.asm \
../AXIS_CPU1/ECap2.asm \
../AXIS_CPU1/Encoder.asm \
../AXIS_CPU1/FlashProg.asm \
../AXIS_CPU1/GpioDriver.asm \
../AXIS_CPU1/Gyro.asm \
../AXIS_CPU1/GyroCommunication.asm \
../AXIS_CPU1/GyroDrv.asm \
../AXIS_CPU1/HardInit.asm \
../AXIS_CPU1/HardInit2.asm \
../AXIS_CPU1/HostCommunication.asm \
../AXIS_CPU1/InternalFlash.asm \
../AXIS_CPU1/ItNav.asm \
../AXIS_CPU1/LedDriver.asm \
../AXIS_CPU1/LowLevel.asm \
../AXIS_CPU1/MainApp.asm \
../AXIS_CPU1/MainApp2.asm \
../AXIS_CPU1/ManState.asm \
../AXIS_CPU1/ManipComRS485.asm \
../AXIS_CPU1/ObjectDict.asm \
../AXIS_CPU1/ObjectDictionary2.asm \
../AXIS_CPU1/ObjectSlave.asm \
../AXIS_CPU1/PackHandler.asm \
../AXIS_CPU1/PieCtrl.asm \
../AXIS_CPU1/PwmDrv.asm \
../AXIS_CPU1/PwmDrv2.asm \
../AXIS_CPU1/Queues.asm \
../AXIS_CPU1/Recorder.asm \
../AXIS_CPU1/Recorder2.asm \
../AXIS_CPU1/SciDrive.asm \
../AXIS_CPU1/SciDrive2.asm \
../AXIS_CPU1/SdRam.asm \
../AXIS_CPU1/ShelfStateNew.asm \
../AXIS_CPU1/ShelfStates.asm \
../AXIS_CPU1/StandardObj.asm \
../AXIS_CPU1/StandardObj2.asm \
../AXIS_CPU1/SysControl.asm \
../AXIS_CPU1/System.asm \
../AXIS_CPU1/TimerArr.asm \
../AXIS_CPU1/TimerArr2.asm \
../AXIS_CPU1/TrapezeProfiler.asm \
../AXIS_CPU1/TrapezeProfiler2.asm \
../AXIS_CPU1/WaksSmachine.asm \
../AXIS_CPU1/asysctl.asm \
../AXIS_CPU1/bgcrc.asm \
../AXIS_CPU1/can.asm \
../AXIS_CPU1/cla.asm \
../AXIS_CPU1/cmpss.asm \
../AXIS_CPU1/cputimer.asm \
../AXIS_CPU1/dac.asm \
../AXIS_CPU1/dcc.asm \
../AXIS_CPU1/dcsm.asm \
../AXIS_CPU1/device.asm \
../AXIS_CPU1/dma.asm \
../AXIS_CPU1/emif.asm \
../AXIS_CPU1/epwm.asm \
../AXIS_CPU1/eqep.asm \
../AXIS_CPU1/escss.asm \
../AXIS_CPU1/f2838x_GlobalVariableDefs.asm \
../AXIS_CPU1/f2838x_defaultisr.asm \
../AXIS_CPU1/f2838x_pievect.asm \
../AXIS_CPU1/flash.asm \
../AXIS_CPU1/fsi.asm \
../AXIS_CPU1/gpio.asm \
../AXIS_CPU1/hrcap.asm \
../AXIS_CPU1/hrpwm.asm \
../AXIS_CPU1/i2c.asm \
../AXIS_CPU1/interrupt.asm \
../AXIS_CPU1/ipc.asm \
../AXIS_CPU1/mcbsp.asm \
../AXIS_CPU1/memcfg.asm \
../AXIS_CPU1/sci.asm \
../AXIS_CPU1/sdfm.asm \
../AXIS_CPU1/spi.asm \
../AXIS_CPU1/sysctl.asm \
../AXIS_CPU1/usb.asm \
../AXIS_CPU1/version.asm \
../AXIS_CPU1/xbar.asm 

OBJS += \
./AXIS_CPU1/Adc.obj \
./AXIS_CPU1/AppIsr.obj \
./AXIS_CPU1/AppIsr2.obj \
./AXIS_CPU1/CanDriver.obj \
./AXIS_CPU1/CanResponser.obj \
./AXIS_CPU1/CanSlave.obj \
./AXIS_CPU1/ClaAdcDrv.obj \
./AXIS_CPU1/ClaDrv.obj \
./AXIS_CPU1/Dynamixel.obj \
./AXIS_CPU1/ECap.obj \
./AXIS_CPU1/ECap2.obj \
./AXIS_CPU1/Encoder.obj \
./AXIS_CPU1/FlashProg.obj \
./AXIS_CPU1/GpioDriver.obj \
./AXIS_CPU1/Gyro.obj \
./AXIS_CPU1/GyroCommunication.obj \
./AXIS_CPU1/GyroDrv.obj \
./AXIS_CPU1/HardInit.obj \
./AXIS_CPU1/HardInit2.obj \
./AXIS_CPU1/HostCommunication.obj \
./AXIS_CPU1/InternalFlash.obj \
./AXIS_CPU1/ItNav.obj \
./AXIS_CPU1/LedDriver.obj \
./AXIS_CPU1/LowLevel.obj \
./AXIS_CPU1/MainApp.obj \
./AXIS_CPU1/MainApp2.obj \
./AXIS_CPU1/ManState.obj \
./AXIS_CPU1/ManipComRS485.obj \
./AXIS_CPU1/ObjectDict.obj \
./AXIS_CPU1/ObjectDictionary2.obj \
./AXIS_CPU1/ObjectSlave.obj \
./AXIS_CPU1/PackHandler.obj \
./AXIS_CPU1/PieCtrl.obj \
./AXIS_CPU1/PwmDrv.obj \
./AXIS_CPU1/PwmDrv2.obj \
./AXIS_CPU1/Queues.obj \
./AXIS_CPU1/Recorder.obj \
./AXIS_CPU1/Recorder2.obj \
./AXIS_CPU1/SciDrive.obj \
./AXIS_CPU1/SciDrive2.obj \
./AXIS_CPU1/SdRam.obj \
./AXIS_CPU1/ShelfStateNew.obj \
./AXIS_CPU1/ShelfStates.obj \
./AXIS_CPU1/StandardObj.obj \
./AXIS_CPU1/StandardObj2.obj \
./AXIS_CPU1/SysControl.obj \
./AXIS_CPU1/System.obj \
./AXIS_CPU1/TimerArr.obj \
./AXIS_CPU1/TimerArr2.obj \
./AXIS_CPU1/TrapezeProfiler.obj \
./AXIS_CPU1/TrapezeProfiler2.obj \
./AXIS_CPU1/WaksSmachine.obj \
./AXIS_CPU1/asysctl.obj \
./AXIS_CPU1/bgcrc.obj \
./AXIS_CPU1/can.obj \
./AXIS_CPU1/cla.obj \
./AXIS_CPU1/cmpss.obj \
./AXIS_CPU1/cputimer.obj \
./AXIS_CPU1/dac.obj \
./AXIS_CPU1/dcc.obj \
./AXIS_CPU1/dcsm.obj \
./AXIS_CPU1/device.obj \
./AXIS_CPU1/dma.obj \
./AXIS_CPU1/emif.obj \
./AXIS_CPU1/epwm.obj \
./AXIS_CPU1/eqep.obj \
./AXIS_CPU1/escss.obj \
./AXIS_CPU1/f2838x_GlobalVariableDefs.obj \
./AXIS_CPU1/f2838x_defaultisr.obj \
./AXIS_CPU1/f2838x_pievect.obj \
./AXIS_CPU1/flash.obj \
./AXIS_CPU1/fsi.obj \
./AXIS_CPU1/gpio.obj \
./AXIS_CPU1/hrcap.obj \
./AXIS_CPU1/hrpwm.obj \
./AXIS_CPU1/i2c.obj \
./AXIS_CPU1/interrupt.obj \
./AXIS_CPU1/ipc.obj \
./AXIS_CPU1/mcbsp.obj \
./AXIS_CPU1/memcfg.obj \
./AXIS_CPU1/sci.obj \
./AXIS_CPU1/sdfm.obj \
./AXIS_CPU1/spi.obj \
./AXIS_CPU1/sysctl.obj \
./AXIS_CPU1/usb.obj \
./AXIS_CPU1/version.obj \
./AXIS_CPU1/xbar.obj 

ASM_DEPS += \
./AXIS_CPU1/Adc.d \
./AXIS_CPU1/AppIsr.d \
./AXIS_CPU1/AppIsr2.d \
./AXIS_CPU1/CanDriver.d \
./AXIS_CPU1/CanResponser.d \
./AXIS_CPU1/CanSlave.d \
./AXIS_CPU1/ClaAdcDrv.d \
./AXIS_CPU1/ClaDrv.d \
./AXIS_CPU1/Dynamixel.d \
./AXIS_CPU1/ECap.d \
./AXIS_CPU1/ECap2.d \
./AXIS_CPU1/Encoder.d \
./AXIS_CPU1/FlashProg.d \
./AXIS_CPU1/GpioDriver.d \
./AXIS_CPU1/Gyro.d \
./AXIS_CPU1/GyroCommunication.d \
./AXIS_CPU1/GyroDrv.d \
./AXIS_CPU1/HardInit.d \
./AXIS_CPU1/HardInit2.d \
./AXIS_CPU1/HostCommunication.d \
./AXIS_CPU1/InternalFlash.d \
./AXIS_CPU1/ItNav.d \
./AXIS_CPU1/LedDriver.d \
./AXIS_CPU1/LowLevel.d \
./AXIS_CPU1/MainApp.d \
./AXIS_CPU1/MainApp2.d \
./AXIS_CPU1/ManState.d \
./AXIS_CPU1/ManipComRS485.d \
./AXIS_CPU1/ObjectDict.d \
./AXIS_CPU1/ObjectDictionary2.d \
./AXIS_CPU1/ObjectSlave.d \
./AXIS_CPU1/PackHandler.d \
./AXIS_CPU1/PieCtrl.d \
./AXIS_CPU1/PwmDrv.d \
./AXIS_CPU1/PwmDrv2.d \
./AXIS_CPU1/Queues.d \
./AXIS_CPU1/Recorder.d \
./AXIS_CPU1/Recorder2.d \
./AXIS_CPU1/SciDrive.d \
./AXIS_CPU1/SciDrive2.d \
./AXIS_CPU1/SdRam.d \
./AXIS_CPU1/ShelfStateNew.d \
./AXIS_CPU1/ShelfStates.d \
./AXIS_CPU1/StandardObj.d \
./AXIS_CPU1/StandardObj2.d \
./AXIS_CPU1/SysControl.d \
./AXIS_CPU1/System.d \
./AXIS_CPU1/TimerArr.d \
./AXIS_CPU1/TimerArr2.d \
./AXIS_CPU1/TrapezeProfiler.d \
./AXIS_CPU1/TrapezeProfiler2.d \
./AXIS_CPU1/WaksSmachine.d \
./AXIS_CPU1/asysctl.d \
./AXIS_CPU1/bgcrc.d \
./AXIS_CPU1/can.d \
./AXIS_CPU1/cla.d \
./AXIS_CPU1/cmpss.d \
./AXIS_CPU1/cputimer.d \
./AXIS_CPU1/dac.d \
./AXIS_CPU1/dcc.d \
./AXIS_CPU1/dcsm.d \
./AXIS_CPU1/device.d \
./AXIS_CPU1/dma.d \
./AXIS_CPU1/emif.d \
./AXIS_CPU1/epwm.d \
./AXIS_CPU1/eqep.d \
./AXIS_CPU1/escss.d \
./AXIS_CPU1/f2838x_GlobalVariableDefs.d \
./AXIS_CPU1/f2838x_defaultisr.d \
./AXIS_CPU1/f2838x_pievect.d \
./AXIS_CPU1/flash.d \
./AXIS_CPU1/fsi.d \
./AXIS_CPU1/gpio.d \
./AXIS_CPU1/hrcap.d \
./AXIS_CPU1/hrpwm.d \
./AXIS_CPU1/i2c.d \
./AXIS_CPU1/interrupt.d \
./AXIS_CPU1/ipc.d \
./AXIS_CPU1/mcbsp.d \
./AXIS_CPU1/memcfg.d \
./AXIS_CPU1/sci.d \
./AXIS_CPU1/sdfm.d \
./AXIS_CPU1/spi.d \
./AXIS_CPU1/sysctl.d \
./AXIS_CPU1/usb.d \
./AXIS_CPU1/version.d \
./AXIS_CPU1/xbar.d 

OBJS__QUOTED += \
"AXIS_CPU1\Adc.obj" \
"AXIS_CPU1\AppIsr.obj" \
"AXIS_CPU1\AppIsr2.obj" \
"AXIS_CPU1\CanDriver.obj" \
"AXIS_CPU1\CanResponser.obj" \
"AXIS_CPU1\CanSlave.obj" \
"AXIS_CPU1\ClaAdcDrv.obj" \
"AXIS_CPU1\ClaDrv.obj" \
"AXIS_CPU1\Dynamixel.obj" \
"AXIS_CPU1\ECap.obj" \
"AXIS_CPU1\ECap2.obj" \
"AXIS_CPU1\Encoder.obj" \
"AXIS_CPU1\FlashProg.obj" \
"AXIS_CPU1\GpioDriver.obj" \
"AXIS_CPU1\Gyro.obj" \
"AXIS_CPU1\GyroCommunication.obj" \
"AXIS_CPU1\GyroDrv.obj" \
"AXIS_CPU1\HardInit.obj" \
"AXIS_CPU1\HardInit2.obj" \
"AXIS_CPU1\HostCommunication.obj" \
"AXIS_CPU1\InternalFlash.obj" \
"AXIS_CPU1\ItNav.obj" \
"AXIS_CPU1\LedDriver.obj" \
"AXIS_CPU1\LowLevel.obj" \
"AXIS_CPU1\MainApp.obj" \
"AXIS_CPU1\MainApp2.obj" \
"AXIS_CPU1\ManState.obj" \
"AXIS_CPU1\ManipComRS485.obj" \
"AXIS_CPU1\ObjectDict.obj" \
"AXIS_CPU1\ObjectDictionary2.obj" \
"AXIS_CPU1\ObjectSlave.obj" \
"AXIS_CPU1\PackHandler.obj" \
"AXIS_CPU1\PieCtrl.obj" \
"AXIS_CPU1\PwmDrv.obj" \
"AXIS_CPU1\PwmDrv2.obj" \
"AXIS_CPU1\Queues.obj" \
"AXIS_CPU1\Recorder.obj" \
"AXIS_CPU1\Recorder2.obj" \
"AXIS_CPU1\SciDrive.obj" \
"AXIS_CPU1\SciDrive2.obj" \
"AXIS_CPU1\SdRam.obj" \
"AXIS_CPU1\ShelfStateNew.obj" \
"AXIS_CPU1\ShelfStates.obj" \
"AXIS_CPU1\StandardObj.obj" \
"AXIS_CPU1\StandardObj2.obj" \
"AXIS_CPU1\SysControl.obj" \
"AXIS_CPU1\System.obj" \
"AXIS_CPU1\TimerArr.obj" \
"AXIS_CPU1\TimerArr2.obj" \
"AXIS_CPU1\TrapezeProfiler.obj" \
"AXIS_CPU1\TrapezeProfiler2.obj" \
"AXIS_CPU1\WaksSmachine.obj" \
"AXIS_CPU1\asysctl.obj" \
"AXIS_CPU1\bgcrc.obj" \
"AXIS_CPU1\can.obj" \
"AXIS_CPU1\cla.obj" \
"AXIS_CPU1\cmpss.obj" \
"AXIS_CPU1\cputimer.obj" \
"AXIS_CPU1\dac.obj" \
"AXIS_CPU1\dcc.obj" \
"AXIS_CPU1\dcsm.obj" \
"AXIS_CPU1\device.obj" \
"AXIS_CPU1\dma.obj" \
"AXIS_CPU1\emif.obj" \
"AXIS_CPU1\epwm.obj" \
"AXIS_CPU1\eqep.obj" \
"AXIS_CPU1\escss.obj" \
"AXIS_CPU1\f2838x_GlobalVariableDefs.obj" \
"AXIS_CPU1\f2838x_defaultisr.obj" \
"AXIS_CPU1\f2838x_pievect.obj" \
"AXIS_CPU1\flash.obj" \
"AXIS_CPU1\fsi.obj" \
"AXIS_CPU1\gpio.obj" \
"AXIS_CPU1\hrcap.obj" \
"AXIS_CPU1\hrpwm.obj" \
"AXIS_CPU1\i2c.obj" \
"AXIS_CPU1\interrupt.obj" \
"AXIS_CPU1\ipc.obj" \
"AXIS_CPU1\mcbsp.obj" \
"AXIS_CPU1\memcfg.obj" \
"AXIS_CPU1\sci.obj" \
"AXIS_CPU1\sdfm.obj" \
"AXIS_CPU1\spi.obj" \
"AXIS_CPU1\sysctl.obj" \
"AXIS_CPU1\usb.obj" \
"AXIS_CPU1\version.obj" \
"AXIS_CPU1\xbar.obj" 

ASM_DEPS__QUOTED += \
"AXIS_CPU1\Adc.d" \
"AXIS_CPU1\AppIsr.d" \
"AXIS_CPU1\AppIsr2.d" \
"AXIS_CPU1\CanDriver.d" \
"AXIS_CPU1\CanResponser.d" \
"AXIS_CPU1\CanSlave.d" \
"AXIS_CPU1\ClaAdcDrv.d" \
"AXIS_CPU1\ClaDrv.d" \
"AXIS_CPU1\Dynamixel.d" \
"AXIS_CPU1\ECap.d" \
"AXIS_CPU1\ECap2.d" \
"AXIS_CPU1\Encoder.d" \
"AXIS_CPU1\FlashProg.d" \
"AXIS_CPU1\GpioDriver.d" \
"AXIS_CPU1\Gyro.d" \
"AXIS_CPU1\GyroCommunication.d" \
"AXIS_CPU1\GyroDrv.d" \
"AXIS_CPU1\HardInit.d" \
"AXIS_CPU1\HardInit2.d" \
"AXIS_CPU1\HostCommunication.d" \
"AXIS_CPU1\InternalFlash.d" \
"AXIS_CPU1\ItNav.d" \
"AXIS_CPU1\LedDriver.d" \
"AXIS_CPU1\LowLevel.d" \
"AXIS_CPU1\MainApp.d" \
"AXIS_CPU1\MainApp2.d" \
"AXIS_CPU1\ManState.d" \
"AXIS_CPU1\ManipComRS485.d" \
"AXIS_CPU1\ObjectDict.d" \
"AXIS_CPU1\ObjectDictionary2.d" \
"AXIS_CPU1\ObjectSlave.d" \
"AXIS_CPU1\PackHandler.d" \
"AXIS_CPU1\PieCtrl.d" \
"AXIS_CPU1\PwmDrv.d" \
"AXIS_CPU1\PwmDrv2.d" \
"AXIS_CPU1\Queues.d" \
"AXIS_CPU1\Recorder.d" \
"AXIS_CPU1\Recorder2.d" \
"AXIS_CPU1\SciDrive.d" \
"AXIS_CPU1\SciDrive2.d" \
"AXIS_CPU1\SdRam.d" \
"AXIS_CPU1\ShelfStateNew.d" \
"AXIS_CPU1\ShelfStates.d" \
"AXIS_CPU1\StandardObj.d" \
"AXIS_CPU1\StandardObj2.d" \
"AXIS_CPU1\SysControl.d" \
"AXIS_CPU1\System.d" \
"AXIS_CPU1\TimerArr.d" \
"AXIS_CPU1\TimerArr2.d" \
"AXIS_CPU1\TrapezeProfiler.d" \
"AXIS_CPU1\TrapezeProfiler2.d" \
"AXIS_CPU1\WaksSmachine.d" \
"AXIS_CPU1\asysctl.d" \
"AXIS_CPU1\bgcrc.d" \
"AXIS_CPU1\can.d" \
"AXIS_CPU1\cla.d" \
"AXIS_CPU1\cmpss.d" \
"AXIS_CPU1\cputimer.d" \
"AXIS_CPU1\dac.d" \
"AXIS_CPU1\dcc.d" \
"AXIS_CPU1\dcsm.d" \
"AXIS_CPU1\device.d" \
"AXIS_CPU1\dma.d" \
"AXIS_CPU1\emif.d" \
"AXIS_CPU1\epwm.d" \
"AXIS_CPU1\eqep.d" \
"AXIS_CPU1\escss.d" \
"AXIS_CPU1\f2838x_GlobalVariableDefs.d" \
"AXIS_CPU1\f2838x_defaultisr.d" \
"AXIS_CPU1\f2838x_pievect.d" \
"AXIS_CPU1\flash.d" \
"AXIS_CPU1\fsi.d" \
"AXIS_CPU1\gpio.d" \
"AXIS_CPU1\hrcap.d" \
"AXIS_CPU1\hrpwm.d" \
"AXIS_CPU1\i2c.d" \
"AXIS_CPU1\interrupt.d" \
"AXIS_CPU1\ipc.d" \
"AXIS_CPU1\mcbsp.d" \
"AXIS_CPU1\memcfg.d" \
"AXIS_CPU1\sci.d" \
"AXIS_CPU1\sdfm.d" \
"AXIS_CPU1\spi.d" \
"AXIS_CPU1\sysctl.d" \
"AXIS_CPU1\usb.d" \
"AXIS_CPU1\version.d" \
"AXIS_CPU1\xbar.d" 

ASM_SRCS__QUOTED += \
"../AXIS_CPU1/Adc.asm" \
"../AXIS_CPU1/AppIsr.asm" \
"../AXIS_CPU1/AppIsr2.asm" \
"../AXIS_CPU1/CanDriver.asm" \
"../AXIS_CPU1/CanResponser.asm" \
"../AXIS_CPU1/CanSlave.asm" \
"../AXIS_CPU1/ClaAdcDrv.asm" \
"../AXIS_CPU1/ClaDrv.asm" \
"../AXIS_CPU1/Dynamixel.asm" \
"../AXIS_CPU1/ECap.asm" \
"../AXIS_CPU1/ECap2.asm" \
"../AXIS_CPU1/Encoder.asm" \
"../AXIS_CPU1/FlashProg.asm" \
"../AXIS_CPU1/GpioDriver.asm" \
"../AXIS_CPU1/Gyro.asm" \
"../AXIS_CPU1/GyroCommunication.asm" \
"../AXIS_CPU1/GyroDrv.asm" \
"../AXIS_CPU1/HardInit.asm" \
"../AXIS_CPU1/HardInit2.asm" \
"../AXIS_CPU1/HostCommunication.asm" \
"../AXIS_CPU1/InternalFlash.asm" \
"../AXIS_CPU1/ItNav.asm" \
"../AXIS_CPU1/LedDriver.asm" \
"../AXIS_CPU1/LowLevel.asm" \
"../AXIS_CPU1/MainApp.asm" \
"../AXIS_CPU1/MainApp2.asm" \
"../AXIS_CPU1/ManState.asm" \
"../AXIS_CPU1/ManipComRS485.asm" \
"../AXIS_CPU1/ObjectDict.asm" \
"../AXIS_CPU1/ObjectDictionary2.asm" \
"../AXIS_CPU1/ObjectSlave.asm" \
"../AXIS_CPU1/PackHandler.asm" \
"../AXIS_CPU1/PieCtrl.asm" \
"../AXIS_CPU1/PwmDrv.asm" \
"../AXIS_CPU1/PwmDrv2.asm" \
"../AXIS_CPU1/Queues.asm" \
"../AXIS_CPU1/Recorder.asm" \
"../AXIS_CPU1/Recorder2.asm" \
"../AXIS_CPU1/SciDrive.asm" \
"../AXIS_CPU1/SciDrive2.asm" \
"../AXIS_CPU1/SdRam.asm" \
"../AXIS_CPU1/ShelfStateNew.asm" \
"../AXIS_CPU1/ShelfStates.asm" \
"../AXIS_CPU1/StandardObj.asm" \
"../AXIS_CPU1/StandardObj2.asm" \
"../AXIS_CPU1/SysControl.asm" \
"../AXIS_CPU1/System.asm" \
"../AXIS_CPU1/TimerArr.asm" \
"../AXIS_CPU1/TimerArr2.asm" \
"../AXIS_CPU1/TrapezeProfiler.asm" \
"../AXIS_CPU1/TrapezeProfiler2.asm" \
"../AXIS_CPU1/WaksSmachine.asm" \
"../AXIS_CPU1/asysctl.asm" \
"../AXIS_CPU1/bgcrc.asm" \
"../AXIS_CPU1/can.asm" \
"../AXIS_CPU1/cla.asm" \
"../AXIS_CPU1/cmpss.asm" \
"../AXIS_CPU1/cputimer.asm" \
"../AXIS_CPU1/dac.asm" \
"../AXIS_CPU1/dcc.asm" \
"../AXIS_CPU1/dcsm.asm" \
"../AXIS_CPU1/device.asm" \
"../AXIS_CPU1/dma.asm" \
"../AXIS_CPU1/emif.asm" \
"../AXIS_CPU1/epwm.asm" \
"../AXIS_CPU1/eqep.asm" \
"../AXIS_CPU1/escss.asm" \
"../AXIS_CPU1/f2838x_GlobalVariableDefs.asm" \
"../AXIS_CPU1/f2838x_defaultisr.asm" \
"../AXIS_CPU1/f2838x_pievect.asm" \
"../AXIS_CPU1/flash.asm" \
"../AXIS_CPU1/fsi.asm" \
"../AXIS_CPU1/gpio.asm" \
"../AXIS_CPU1/hrcap.asm" \
"../AXIS_CPU1/hrpwm.asm" \
"../AXIS_CPU1/i2c.asm" \
"../AXIS_CPU1/interrupt.asm" \
"../AXIS_CPU1/ipc.asm" \
"../AXIS_CPU1/mcbsp.asm" \
"../AXIS_CPU1/memcfg.asm" \
"../AXIS_CPU1/sci.asm" \
"../AXIS_CPU1/sdfm.asm" \
"../AXIS_CPU1/spi.asm" \
"../AXIS_CPU1/sysctl.asm" \
"../AXIS_CPU1/usb.asm" \
"../AXIS_CPU1/version.asm" \
"../AXIS_CPU1/xbar.asm" 

OPT_SRCS__QUOTED += \
"../AXIS_CPU1/ccsObjs.opt" 


